services:
  pgdatabase:
    image: postgres:18
    container_name: meteo_pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: meteo123
      POSTGRES_DB: meteo
    ports:
      - "5433:5432"
    volumes:
      - meteo_pgdata:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d meteo"]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: meteo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8085:80"
    depends_on:
      pgdatabase:
        condition: service_healthy

volumes:
  meteo_pgdata: