services:
  pgdatabase:
    image: postgres:18
    container_name: meteo_pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: meteo123
      POSTGRES_DB: meteo
    ports:
      - "5433:5432"
    volumes:
      - meteo_pgdata:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d meteo"]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: meteo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8085:80"
    depends_on:
      pgdatabase:
        condition: service_healthy

  airflow-init:
    image: apache/airflow:2.9.3
    container_name: airflow_init
    depends_on:
      pgdatabase:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://root:meteo123@pgdatabase:5432/meteo
      AIRFLOW__WEBSERVER__SECRET_KEY: "midterm_secret_key"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    command:
      - bash
      - -c
      - airflow db migrate && airflow users create --username admin --password admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: airflow_webserver
    restart: always
    depends_on:
      pgdatabase:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://root:meteo123@pgdatabase:5432/meteo
      AIRFLOW__WEBSERVER__SECRET_KEY: "midterm_secret_key"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    ports:
      - "8086:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: airflow_scheduler
    restart: always
    depends_on:
      pgdatabase:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://root:meteo123@pgdatabase:5432/meteo
      AIRFLOW__WEBSERVER__SECRET_KEY: "midterm_secret_key"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    command: scheduler

volumes:
  meteo_pgdata: