services:
  pgdatabase:
    image: postgres:18
    container_name: meteo_pgdatabase
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - meteo_pgdata:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: meteo_pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8085:80"
    depends_on:
      pgdatabase:
        condition: service_healthy

  airflow-init:
    image: deng_airflow:2.9.3
    container_name: airflow_init
    env_file:
      - .env
    depends_on:
      pgdatabase:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      BQ_DATASET_ID: ${BQ_DATASET_ID}
      BQ_CITY_TABLE_ID: ${BQ_CITY_TABLE_ID}
      BQ_STATION_TABLE_ID: ${BQ_STATION_TABLE_ID}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    command:
      - bash
      - -c
      - |
        airflow db migrate &&
        airflow users create \
          --username "$$AIRFLOW_USERNAME" \
          --password "$$AIRFLOW_PASSWORD" \
          --firstname "$$AIRFLOW_FIRSTNAME" \
          --lastname "$$AIRFLOW_LASTNAME" \
          --role Admin \
          --email "$$AIRFLOW_EMAIL" || true

  airflow-webserver:
    image: deng_airflow:2.9.3
    container_name: airflow_webserver
    restart: always
    env_file:
      - .env
    depends_on:
      pgdatabase:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      BQ_DATASET_ID: ${BQ_DATASET_ID}
      BQ_CITY_TABLE_ID: ${BQ_CITY_TABLE_ID}
      BQ_STATION_TABLE_ID: ${BQ_STATION_TABLE_ID}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    ports:
      - "8086:8080"
    command: webserver

  airflow-scheduler:
    image: deng_airflow:2.9.3
    container_name: airflow_scheduler
    restart: always
    env_file:
      - .env
    depends_on:
      pgdatabase:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      BQ_DATASET_ID: ${BQ_DATASET_ID}
      BQ_CITY_TABLE_ID: ${BQ_CITY_TABLE_ID}
      BQ_STATION_TABLE_ID: ${BQ_STATION_TABLE_ID}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    command: scheduler

volumes:
  meteo_pgdata: